rimosse helm var

diff --git a/.github/workflows/deploy-sub.yaml b/.github/workflows/deploy-sub.yaml
--- a/.github/workflows/deploy-sub.yaml
+++ b/.github/workflows/deploy-sub.yaml
@@ -1,6 +1,6 @@
 name: Deploy (sub)
 
-on: 
+on:
   workflow_dispatch:
     inputs:
       environment:
@@ -18,10 +18,8 @@ defaults:
 
 env:
   SCRIPTS_FOLDER: "./interop-infra-commons/scripts/helm"
-  HELM_REPO_URL: "https://pagopa.github.io/"  # REPO PUBBLICO DELLE CHARTS
-  HELM_REPO_NAME: "interop-charts"
 
-jobs:  
+jobs:
   workflow_setup:
     name: Setup Steps
     runs-on: ubuntu-latest
@@ -49,19 +47,33 @@ jobs:
           path: /tmp/cache
           key: simulation-${{ inputs.environment }}-${{ steps.calculate-hash.outputs.hash }}
 
-      - name: Pull and Extract Charts if Cache Miss
-        if: steps.cache-restore.outputs.cache-hit != 'true'
+      - name: Download and Extract Charts
         run: |
           mkdir -p /tmp/cache
-          cd $GITHUB_WORKSPACE  # Ti assicura di essere nella directory del repo.
 
-          charts=$(yq '.dependencies[].repository + " " + .dependencies[].name + " " + .dependencies[].version' Chart.yaml | paste - - -)
-          while IFS=$'\t' read -r repo name version; do
-            echo "Pulling chart $name version $version from $repo"
-            helm repo add temp-repo $repo || true
-            helm pull temp-repo/$name --version $version --destination /tmp/cache
-            tar -xzf /tmp/cache/$name-$version.tgz -C /tmp/cache/
-          done <<< "$charts"
+          if [ -f "Chart.yaml" ]; then
+            charts=$(yq '.dependencies[] | .repository + " " + .name + " " + .version' Chart.yaml | paste - - -)
+            while IFS=$'\t' read -r repo name version; do
+              echo "Processing chart: $name version: $version from $repo"
+
+              if [ ! -f "/tmp/cache/$name-$version.tgz" ]; then
+                echo "Downloading chart: $name-$version.tgz"
+                curl -sSL "$repo/$name-$version.tgz" -o "/tmp/cache/$name-$version.tgz"
+              else
+                echo "Chart $name-$version already in cache, skipping download."
+              fi
+
+              if [ ! -d "/tmp/cache/$name" ]; then
+                echo "Extracting chart: $name-$version.tgz"
+                tar -xzf "/tmp/cache/$name-$version.tgz" -C /tmp/cache/
+              else
+                echo "Chart $name already extracted, skipping."
+              fi
+            done <<< "$charts"
+          else
+            echo "Chart.yaml not found. Skipping chart processing."
+          fi
+        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
 
       - id: set-outputs
         run: |
@@ -86,14 +98,6 @@ jobs:
           path: /tmp/cache
           key: simulation-${{ inputs.environment }}-${{ steps.calculate-hash.outputs.hash }}
 
-      - name: Cache Status
-        run: |
-          if [ "${{ steps.cache-restore.outputs.cache-hit }}" == "true" ]; then
-            echo "::info::Deploy with cache"
-          else
-            echo "::info::Deploy without cache"
-          fi
-
   simulate_microservices:
     name: Simulate Microservice Deploy - ${{ matrix.microservice }}
     needs: workflow_setup
@@ -112,7 +116,7 @@ jobs:
       - name: Simulate Microservice Deploy
         run: |
           echo "::info::Simulating deploy for microservice: ${{ matrix.microservice }}"
-          echo "::info::This is a dry run. No real deployment executed."
+          echo "::info::Deploy with caching completed."
 
   simulate_cronjobs:
     name: Simulate Cronjob Deploy - ${{ matrix.cronjob }}
@@ -132,4 +136,4 @@ jobs:
       - name: Simulate Cronjob Deploy
         run: |
           echo "::info::Simulating deploy for cronjob: ${{ matrix.cronjob }}"
-          echo "::info::This is a dry run. No real deployment executed."
+          echo "::info::Deploy with caching completed."
